### ISSUE TITLE
1 main.go:34] hover IP needs to be updated. Hover: x.x.x.x, Actual: y.y.y.y

### ISSUE THREAD

**Issue by diegocerdan** [taoofshawn/hoverDdns#1]
After some time running the docker service, I start getting wrong WAN IP detection.

The actual x.x.x.x is 64.98.145.30, located in a different country.

And I've also seen x.x.x.x as 4.4.4.4

**Comment by taoofshawn** [comment]
The WAN IP is determined by visiting an external site: https://api.ipify.org

Next time you see the wrong WAN IP. 
Please visit https://api.ipify.org to confirm if you it also shows the incorrect WAN IP. 

Also, visit this alternative:  https://ifconfig.co/
If the alternative is correct I will switch the program to use that one instead.
